_target_: src.models.centernet_module.CenterNet

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0005
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: true
  milestones: [30, 80]
  gamma: 0.1

gaussian_iou: 0.7

net:
  num_classes: ???
